
####
GET http://localhost:5219/api/BorrowerInformation HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwianRpIjoiZGMzZjZmN2UtZTczNy00ODZjLTk3NzQtMzljNThjMmQzNjdjIiwic3ViIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwiZXhwIjoxNzI1OTkyMzU2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ._QXt8r1WHX4UhYwuJjEPcPCx7qEKyJN1KtVUhf6nvL0

Content-type: application/json

{
  
}
####
GET http://localhost:5219/api/LoanInformation HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwianRpIjoiZGMzZjZmN2UtZTczNy00ODZjLTk3NzQtMzljNThjMmQzNjdjIiwic3ViIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwiZXhwIjoxNzI1OTkyMzU2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ._QXt8r1WHX4UhYwuJjEPcPCx7qEKyJN1KtVUhf6nvL0
Content-type: application/json

{
  
}


###
GET http://localhost:5219/api/RelativeInformation HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwianRpIjoiNWY5NjA5NDUtMGVkMC00NDk4LTgwM2UtYmEyODY5ODA0ZDc2Iiwic3ViIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwiZXhwIjoxNzIwMDkwMjI3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ._JqhJY6JcHa6ux0mFZ0Ju24M10PiJMvFPm8NlkAhngU

{
   
}

###

GET http://localhost:5219/api/LoanDone HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwianRpIjoiZGMzZjZmN2UtZTczNy00ODZjLTk3NzQtMzljNThjMmQzNjdjIiwic3ViIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwiZXhwIjoxNzI1OTkyMzU2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ._QXt8r1WHX4UhYwuJjEPcPCx7qEKyJN1KtVUhf6nvL0

{
  
}
####
GET http://localhost:5219/api/LoanInformation HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwianRpIjoiZGMzZjZmN2UtZTczNy00ODZjLTk3NzQtMzljNThjMmQzNjdjIiwic3ViIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwiZXhwIjoxNzI1OTkyMzU2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ._QXt8r1WHX4UhYwuJjEPcPCx7qEKyJN1KtVUhf6nvL0

{

}


####
PUT http://localhost:5219/api/BorrowerInformation/7 HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZjIwYmMzN2ItOGJjZC00ZGZjLTlhOWUtOTJjNGExMGJhZDhiIiwianRpIjoiMjU1YzQwYmItZmEwYi00M2FiLWE1YTItYjE1YWJiMGJmZTcwIiwic3ViIjoiZjIwYmMzN2ItOGJjZC00ZGZjLTlhOWUtOTJjNGExMGJhZDhiIiwiZXhwIjoxNzIyODU5MTg0LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.tfFZ4Rdg7BBQQNdADVnOgcG7r2yniec80-D3z6UafiU

{
   "FullName": "yteeeesssss",
  "PhoneNumber": "123456789",
  "Email": "johndoe@example.com",
  "IdentityCardNumber": "1234567890",
  "DateOfIssue": "2024-05-05T00:00:00",
  "PlaceOfIssue": "Some place",
  "Gender": 0,
  "DateOfBirth": "1990-01-01T00:00:00",
  "Hometown": "Hometown",
  "Address": "123 Main Street",
  "ImageBack": "base64-encoded-image-back",
  "ImageFront": "base64-encoded-image-front",
  "Portrait": "base64-encoded-portrait",
  "LoanDone": 1,
  "Note": "Some note"
   
}

####
DELETE http://localhost:5219/api/User/1 HTTP/1.1
Content-Type: application/json

{}

###
POST http://localhost:5219/api/User 
Content-Type: application/json

{
    "UserName": "nguyenvanA", 
    "Email": "nguyenvana@example.com", 
    "Password": "password123", 
    "idRole": 1 
}


###
POST http://localhost:5219/api/AccountHolderInformation 
Content-Type: application/json

{
   {
    "UserId": 1, 
    "FullName": "Nguyễn Văn A",
    "PhoneNumber": "0987654321",
    "IdentityCardNumber": "123456789",
    "DateOfIssue": "2000-01-01", 
    "PlaceOfIssue": "Hà Nội",
    "Gender": "Nam",
    "DateOfBirth": "1990-01-01", 
    "Hometown": "Hà Nội",
    "Address": "Số 10, Phố Hòa Bình, Quận Hai Bà Trưng, Hà Nội",
    "ImageBack": "link_to_image_back.jpg", 
    "ImageFront": "link_to_image_front.jpg" 
    }

}

###
POST http://localhost:5219/api/BorrowerInformation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwianRpIjoiNWMxZjg3OTMtODgxYi00MzhiLTkxYTMtY2EyMjE5ZWMyNDJmIiwic3ViIjoiZGQ1NWQ1NWMtOWRhNS00NzQ1LWIxNjktYWY0YTI1ZTBjYmM1IiwiZXhwIjoxNzI0NzU1MTM2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.bnkCG3TSc0aVwfWCZrtoaJJM3mPPyU2-3IypM3j8kCk

{
  "FullName": "timestampsss222",
  "PhoneNumber": "123456789",
  "Email": "johndoe@example.com",
  "IdentityCardNumber": "1234567890",
  "DateOfIssue": "2024-05-05T00:00:00",
  "PlaceOfIssue": "Some place",
  "Gender": 0,
  "DateOfBirth": "1990-01-01T00:00:00",
  "Hometown": "Hometown",
  "Address": "123 Main Street",
  "ImageBack": "base64-encoded-image-back",
  "ImageFront": "base64-encoded-image-front",
  "Portrait": "base64-encoded-portrait",
  "LoanDone": 1,
  "Note": "Some note"
}



#####
POST http://localhost:5219/api/LoanDone 
Content-Type: application/json

{
    "UserId": "4e9538bc-920b-4238-b427-601f627a2dbf",
    "LoanInformationId":3,
    "BorrowerInformationId":2,
    "Lender": "ABC Bank",
    "LoanType": "Mortgage",
    "LoanPurpose": "Home purchase",
    "LoanAmount": 200000,
    "InterestRate": 5.5,
    "LoanTerm": 30,
    "LoanDate": "2024-03-31T00:00:00",
    "RepaymentDate": "2054-03-31T00:00:00"
}

###
POST http://localhost:5219/api/LoanInformation 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwianRpIjoiZGUxOTg5MzMtYjU1MC00YmFhLWI3NDktM2E2NWZiMzU0ZWI0Iiwic3ViIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwiZXhwIjoxNzIyMjMwMTI3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.jojTQP05q7lLfHs7mzaDVtydIJo2dW0cvO5dLCTRlLg


{
    "LoanInformationName": "ttaaaahhhhh",
    "BorrowerId": 4,
    "Lender": "ABC Bank",
    "LoanType": 0,
    "LoanPurpose": "Home purchase",
    "LoanAmount": 800000,
    "InterestRate": 5.5,
    "LoanTerm": 30,
    "LoanDate": "2024-03-31T00:00:00",
    "RepaymentDate": "2054-03-31T00:00:00",
    "IsInstallment": 0,
    "MonthlyPayment": 0,
    "Note": "Some notes here"
}



###
POST http://localhost:5219/api/Authenticate/register HTTP/1.1
Content-Type: application/json

{
    "Username": "admin12",
    "Password": "Admin12@123V",
    "Email": "admin12@123V"
}


###
POST http://localhost:5219/api/Authenticate/register-admin HTTP/1.1
Content-Type: application/json

{
    "Username": "Van14",
    "Password": "Van14082004!",
    "Email": "Hau12@gmail.com"
}
###

###
DELETE  http://localhost:5219/api/BorrowerInformation/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwianRpIjoiYzZhMzAzNDAtMTc4YS00MjljLTgyMjQtNzY1MjVkZjJiYzgxIiwic3ViIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwiZXhwIjoxNzIyNjgwMzI4LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.RnbGevvE2_2hUvwqcKt7gpFcLv_EOC_UCFd47PsC-ko

{
   
}



###
POST http://localhost:5219/api/ScanInformation HTTP/1.1
Content-Type:application/json

{
    "imagePaths": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYCMjisEGRSJfbgVSZ5dyxwifc10Cfb8PXBQ&s",
}


###

POST http://localhost:5219/api/LoanContract
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwianRpIjoiNjIwZGM4YjgtNjlmYS00YzUwLTg4YjQtYWZjN2NhM2U0OGQxIiwic3ViIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwiZXhwIjoxNzIyMjcyMDYxLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.nNy9IksjTOnIYAc4R2RRVIc-W5NRJKcRvrdp92-Jy_Y

{
    "LoanInformationId": 1,
    "BorrowerInformationId": 1,
    "LoanRequestFormImage": "ABC Bank",
    "IncomeProofImage": "Mortgage",
    "CollateralImage": "Home purchase",
    "CompartmentId": "trong tủ đồ"
}

###
POST http://localhost:5219/api/Authenticate/login HTTP/1.1
Content-Type:application/json

{
    "UserName": "admin12",
    "Password": "Admin12@123V"
}

#####
POST http://localhost:5219/api/LoanRepayment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwianRpIjoiY2RmNWEzYjYtMzU2YS00YzRjLWE5MmItOTcyNTUzNmE2MGMyIiwic3ViIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwiZXhwIjoxNzIyNjE1NzAwLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.X-VLp2_7AO820DWSzbVxy9CgeFAZ9dRO-XbMtsjWNAE

{
  "LoanInformationId": 4,
  "BorrowerInformationId": 4,
  "AmountPaid": 300000, 
  "PaymentDate": "2024-03-31T00:00:00",
  "Note": "Home purchase222"
}

####
GET http://localhost:5219/api/BorrowerInformation/4 HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwianRpIjoiYzZhMzAzNDAtMTc4YS00MjljLTgyMjQtNzY1MjVkZjJiYzgxIiwic3ViIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwiZXhwIjoxNzIyNjgwMzI4LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.RnbGevvE2_2hUvwqcKt7gpFcLv_EOC_UCFd47PsC-ko

{

}
####
GET http://localhost:5219/api/LoanRepayment HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwianRpIjoiY2RmNWEzYjYtMzU2YS00YzRjLWE5MmItOTcyNTUzNmE2MGMyIiwic3ViIjoiNDhkY2M1NTUtNjM5NS00NTQwLWJiNjMtYzJiZDQxYTcwY2JkIiwiZXhwIjoxNzIyNjE1NzAwLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.X-VLp2_7AO820DWSzbVxy9CgeFAZ9dRO-XbMtsjWNAE

{

}