
####
GET http://localhost:5219/api/BorrowerInformation HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwianRpIjoiYmQxYTM4ZjAtMTI2MS00NmZkLTgxZTYtMTBmZWNiMGI1MDA0Iiwic3ViIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwiZXhwIjoxNzE5NzU0OTg3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.FHl9ffNl426AoqdhJa5RhOis2slFcPU_3uNw-AV6YjA

Content-type: application/json

{
  
}
####
GET http://localhost:5219/api/LoanInformation HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwianRpIjoiYjM2N2FjMmYtZGE4Yy00MDFkLWE4MmMtNzg3N2RkNDMwMDhmIiwic3ViIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwiZXhwIjoxNzIxNjI4ODMzLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.1MiyXVs0L_VWAiJV3AnbWzofMeH3wWxj_KTC6m3i2tc

{
  
}


###
GET http://localhost:5219/api/RelativeInformation HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwianRpIjoiNWY5NjA5NDUtMGVkMC00NDk4LTgwM2UtYmEyODY5ODA0ZDc2Iiwic3ViIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwiZXhwIjoxNzIwMDkwMjI3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ._JqhJY6JcHa6ux0mFZ0Ju24M10PiJMvFPm8NlkAhngU

{
   
}
###

POST http://localhost:5219/api/RelativeInformation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwianRpIjoiZjg0MWU1ZDYtZjYwZi00Y2U0LTk2NjYtZTY5MzJiMzg2N2E3Iiwic3ViIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwiZXhwIjoxNzE5OTQ0ODYyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ._NDaA5FHbJ-adQoaiWw8cjBqsXDw1Z7moaZ4jVKMatw

{
"borrowerId": 12,
"fullName": "Nguyễn Văn A",
"phoneNumber": "0123456789",
"email": "nguyenvana@example.com",
"identityCardNumber": "123456789",
"dateOfIssue": "1990-01-01T00:00:00",
"placeOfIssue": "Hà Nội",
"gender":1,
"dateOfBirth": "1990-01-01T00:00:00",
"hometown": "Hà Nội",
"address": "Số 1, Đường ABC, Quận XYZ, Thành phố Hà Nội",
"imageBack": "link-to-image-back",
"imageFront": "link-to-image-front",
"portrait": "link-to-portrait-image",
"note": "Ghi chú cho người thân"
    }
###

GET http://localhost:5219/api/LoanDone HTTP/1.1
Content-type: application/json

{
  
}
####
GET http://localhost:5219/api/LoanInformation HTTP/1.1
Content-type: application/json

{

}


####
PUT http://localhost:5219/api/Product HTTP/1.1
Content-type: application/json

{
    "Id": 3,
    "Name":"Test API test",
    "Description": "Description for Product 12",
    "QuantityInStock": 22,
    "Price": 1.992,
    "Category": "Category 00",
    "transparency": 0
}

####
DELETE http://localhost:5219/api/User/1 HTTP/1.1
Content-Type: application/json

{}

###
POST http://localhost:5219/api/User 
Content-Type: application/json

{
    "UserName": "nguyenvanA", 
    "Email": "nguyenvana@example.com", 
    "Password": "password123", 
    "idRole": 1 
}


###
POST http://localhost:5219/api/AccountHolderInformation 
Content-Type: application/json

{
   {
    "UserId": 1, 
    "FullName": "Nguyễn Văn A",
    "PhoneNumber": "0987654321",
    "IdentityCardNumber": "123456789",
    "DateOfIssue": "2000-01-01", 
    "PlaceOfIssue": "Hà Nội",
    "Gender": "Nam",
    "DateOfBirth": "1990-01-01", 
    "Hometown": "Hà Nội",
    "Address": "Số 10, Phố Hòa Bình, Quận Hai Bà Trưng, Hà Nội",
    "ImageBack": "link_to_image_back.jpg", 
    "ImageFront": "link_to_image_front.jpg" 
    }

}
###
POST http://localhost:5219/api/Authenticate/login HTTP/1.1
Content-Type:application/json

{
    "UserName": "admin11",
    "Password": "Admin11@123V"
}
###
POST http://localhost:5219/api/BorrowerInformation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4xMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwianRpIjoiNzNkOTczY2MtODBlMy00NjUzLWExYmItNjc2YzBmOGM2NjNiIiwic3ViIjoiNjJjMWUwOTgtYzBkMC00Zjc3LTgyZmYtNWU1Mzc4MTRmZjAzIiwiZXhwIjoxNzE5NzQ3MzgwLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.bD0SzUDenUFWDf7pXCkXgqJs8ZPJG1f_LIqD34DiUVw

{
  "FullName": "teslaij2222",
  "PhoneNumber": "123456789",
  "Email": "johndoe@example.com",
  "IdentityCardNumber": "1234567890",
  "DateOfIssue": "2024-05-05T00:00:00",
  "PlaceOfIssue": "Some place",
  "Gender": 0, 
  "DateOfBirth": "1990-01-01T00:00:00",
  "Hometown": "Hometown",
  "Address": "123 Main Street",
  "ImageBack": "base64-encoded-image-back",
  "ImageFront": "base64-encoded-image-front",
  "Portrait": "base64-encoded-portrait",
  "LoanDone": 1, 
  "Note": "Some note"
}


#####
POST http://localhost:5219/api/LoanDone 
Content-Type: application/json

{
    "UserId": "4e9538bc-920b-4238-b427-601f627a2dbf",
    "LoanInformationId":3,
    "BorrowerInformationId":2,
    "Lender": "ABC Bank",
    "LoanType": "Mortgage",
    "LoanPurpose": "Home purchase",
    "LoanAmount": 200000,
    "InterestRate": 5.5,
    "LoanTerm": 30,
    "LoanDate": "2024-03-31T00:00:00",
    "RepaymentDate": "2054-03-31T00:00:00"
}

###
POST http://localhost:5219/api/LoanInformation 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdFVTZWVyMiIsIklEIjoiNWQ4MGYxODktN2I3Ny00NTFmLTg1N2YtNjY5MmZjMzRlNTZjIiwianRpIjoiZjE5NjllZjMtMjdkMy00MDBjLWFhOWItNzE4NjAwNzE2NzZiIiwiZXhwIjoxNzE3ODcyMTY3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.HFOWStv-2fcMEKtgukmJejtsKH47dvT7ZshDUNE7lmQ


{
    "LoanInformationName": "LoanInformation test1",
    "BorrowerId": 42,
    "Lender": "ABC Bank",
    "LoanType": 0,
    "LoanPurpose": "Home purchase",
    "LoanAmount": 200000,
    "InterestRate": 5.5,
    "LoanTerm": 30,
    "LoanDate": "2024-03-31T00:00:00",
    "RepaymentDate": "2054-03-31T00:00:00",
    "IsInstallment": 0,
    "MonthlyPayment": 0,
    "Note": "Some notes here"
}



###
POST http://localhost:5219/api/Authenticate/register HTTP/1.1
Content-Type: application/json

{
    "Username": "admin11",
    "Password": "Admin11@123V",
    "Email": "admin11@123V"
}


###
POST http://localhost:5219/api/Authenticate/register-admin HTTP/1.1
Content-Type: application/json

{
    "Username": "Van14",
    "Password": "Van14082004!",
    "Email": "Hau12@gmail.com"
}
###

###
DELETE  http://localhost:5219/api/BorrowerInformation/9 HTTP/1.1
Content-Type: application/json

{
   
}



###
POST http://localhost:5219/api/ScanInformation HTTP/1.1
Content-Type:application/json

{
    "imagePaths": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYCMjisEGRSJfbgVSZ5dyxwifc10Cfb8PXBQ&s",
}